# Generated by Django 5.1.2 on 2024-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='puplication_year',
            field=models.DateField(),
        ),
    ]
