# Generated by Django 5.1.2 on 2024-11-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'permissions': [('can_hide_post', 'Can hide post')]},
        ),
    ]
